name: Upload Markdown to R2

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install boto3
        run: pip install boto3

      - name: Detect Added Markdown Files
        run: |
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} | grep '^A' | cut -f2 | grep '\.md$' > added_md_files.txt
          cat added_md_files.txt
          if [ ! -s added_md_files.txt ]; then echo "No new Markdown files to upload." && exit 0; fi

      - name: Upload to R2
        run: python3 upload_to_r2.py < added_md_files.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ENDPOINT_URL: ${{ secrets.R2_ENDPOINT_URL }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
